version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # Set the root password
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"  # Make sure 3306 is available
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
        - ./database/ecommerce_application.sql:/docker-entrypoint-initdb.d/ecommerce_application.sql
    environment:
      DB_HOST: db  # Use 'db' here as the MySQL service name
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
